// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cookie_store.proto

package com.example.composepractice;

/**
 * Protobuf type {@code CookieInfo}
 */
public  final class CookieInfo extends
    com.google.protobuf.GeneratedMessageLite<
        CookieInfo, CookieInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:CookieInfo)
    CookieInfoOrBuilder {
  private CookieInfo() {
    name_ = "";
    value_ = "";
    domain_ = "";
    path_ = "";
  }
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.String name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>string name = 1;</code>
   * @param value The name to set.
   */
  private void setName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    name_ = value;
  }
  /**
   * <code>string name = 1;</code>
   */
  private void clearName() {
    
    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>string name = 1;</code>
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    name_ = value.toStringUtf8();
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private java.lang.String value_;
  /**
   * <code>string value = 2;</code>
   * @return The value.
   */
  @java.lang.Override
  public java.lang.String getValue() {
    return value_;
  }
  /**
   * <code>string value = 2;</code>
   * @return The bytes for value.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getValueBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(value_);
  }
  /**
   * <code>string value = 2;</code>
   * @param value The value to set.
   */
  private void setValue(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    value_ = value;
  }
  /**
   * <code>string value = 2;</code>
   */
  private void clearValue() {
    
    value_ = getDefaultInstance().getValue();
  }
  /**
   * <code>string value = 2;</code>
   * @param value The bytes for value to set.
   */
  private void setValueBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    value_ = value.toStringUtf8();
  }

  public static final int EXPIRESAT_FIELD_NUMBER = 3;
  private long expiresAt_;
  /**
   * <code>int64 expiresAt = 3;</code>
   * @return The expiresAt.
   */
  @java.lang.Override
  public long getExpiresAt() {
    return expiresAt_;
  }
  /**
   * <code>int64 expiresAt = 3;</code>
   * @param value The expiresAt to set.
   */
  private void setExpiresAt(long value) {
    
    expiresAt_ = value;
  }
  /**
   * <code>int64 expiresAt = 3;</code>
   */
  private void clearExpiresAt() {
    
    expiresAt_ = 0L;
  }

  public static final int DOMAIN_FIELD_NUMBER = 4;
  private java.lang.String domain_;
  /**
   * <code>string domain = 4;</code>
   * @return The domain.
   */
  @java.lang.Override
  public java.lang.String getDomain() {
    return domain_;
  }
  /**
   * <code>string domain = 4;</code>
   * @return The bytes for domain.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDomainBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(domain_);
  }
  /**
   * <code>string domain = 4;</code>
   * @param value The domain to set.
   */
  private void setDomain(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    domain_ = value;
  }
  /**
   * <code>string domain = 4;</code>
   */
  private void clearDomain() {
    
    domain_ = getDefaultInstance().getDomain();
  }
  /**
   * <code>string domain = 4;</code>
   * @param value The bytes for domain to set.
   */
  private void setDomainBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    domain_ = value.toStringUtf8();
  }

  public static final int PATH_FIELD_NUMBER = 5;
  private java.lang.String path_;
  /**
   * <code>string path = 5;</code>
   * @return The path.
   */
  @java.lang.Override
  public java.lang.String getPath() {
    return path_;
  }
  /**
   * <code>string path = 5;</code>
   * @return The bytes for path.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPathBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(path_);
  }
  /**
   * <code>string path = 5;</code>
   * @param value The path to set.
   */
  private void setPath(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    path_ = value;
  }
  /**
   * <code>string path = 5;</code>
   */
  private void clearPath() {
    
    path_ = getDefaultInstance().getPath();
  }
  /**
   * <code>string path = 5;</code>
   * @param value The bytes for path to set.
   */
  private void setPathBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    path_ = value.toStringUtf8();
  }

  public static final int SECURE_FIELD_NUMBER = 6;
  private boolean secure_;
  /**
   * <code>bool secure = 6;</code>
   * @return The secure.
   */
  @java.lang.Override
  public boolean getSecure() {
    return secure_;
  }
  /**
   * <code>bool secure = 6;</code>
   * @param value The secure to set.
   */
  private void setSecure(boolean value) {
    
    secure_ = value;
  }
  /**
   * <code>bool secure = 6;</code>
   */
  private void clearSecure() {
    
    secure_ = false;
  }

  public static final int HTTPONLY_FIELD_NUMBER = 7;
  private boolean httpOnly_;
  /**
   * <code>bool httpOnly = 7;</code>
   * @return The httpOnly.
   */
  @java.lang.Override
  public boolean getHttpOnly() {
    return httpOnly_;
  }
  /**
   * <code>bool httpOnly = 7;</code>
   * @param value The httpOnly to set.
   */
  private void setHttpOnly(boolean value) {
    
    httpOnly_ = value;
  }
  /**
   * <code>bool httpOnly = 7;</code>
   */
  private void clearHttpOnly() {
    
    httpOnly_ = false;
  }

  public static final int HOSTONLY_FIELD_NUMBER = 8;
  private boolean hostOnly_;
  /**
   * <code>bool hostOnly = 8;</code>
   * @return The hostOnly.
   */
  @java.lang.Override
  public boolean getHostOnly() {
    return hostOnly_;
  }
  /**
   * <code>bool hostOnly = 8;</code>
   * @param value The hostOnly to set.
   */
  private void setHostOnly(boolean value) {
    
    hostOnly_ = value;
  }
  /**
   * <code>bool hostOnly = 8;</code>
   */
  private void clearHostOnly() {
    
    hostOnly_ = false;
  }

  public static final int PERSISTENT_FIELD_NUMBER = 9;
  private boolean persistent_;
  /**
   * <code>bool persistent = 9;</code>
   * @return The persistent.
   */
  @java.lang.Override
  public boolean getPersistent() {
    return persistent_;
  }
  /**
   * <code>bool persistent = 9;</code>
   * @param value The persistent to set.
   */
  private void setPersistent(boolean value) {
    
    persistent_ = value;
  }
  /**
   * <code>bool persistent = 9;</code>
   */
  private void clearPersistent() {
    
    persistent_ = false;
  }

  public static com.example.composepractice.CookieInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.composepractice.CookieInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.composepractice.CookieInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.composepractice.CookieInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.composepractice.CookieInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.composepractice.CookieInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.composepractice.CookieInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.composepractice.CookieInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.composepractice.CookieInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.composepractice.CookieInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.composepractice.CookieInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.composepractice.CookieInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.composepractice.CookieInfo prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code CookieInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.composepractice.CookieInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:CookieInfo)
      com.example.composepractice.CookieInfoOrBuilder {
    // Construct using com.example.composepractice.CookieInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      return instance.getValue();
    }
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      return instance.getValueBytes();
    }
    /**
     * <code>string value = 2;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(
        java.lang.String value) {
      copyOnWrite();
      instance.setValue(value);
      return this;
    }
    /**
     * <code>string value = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      copyOnWrite();
      instance.clearValue();
      return this;
    }
    /**
     * <code>string value = 2;</code>
     * @param value The bytes for value to set.
     * @return This builder for chaining.
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setValueBytes(value);
      return this;
    }

    /**
     * <code>int64 expiresAt = 3;</code>
     * @return The expiresAt.
     */
    @java.lang.Override
    public long getExpiresAt() {
      return instance.getExpiresAt();
    }
    /**
     * <code>int64 expiresAt = 3;</code>
     * @param value The expiresAt to set.
     * @return This builder for chaining.
     */
    public Builder setExpiresAt(long value) {
      copyOnWrite();
      instance.setExpiresAt(value);
      return this;
    }
    /**
     * <code>int64 expiresAt = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearExpiresAt() {
      copyOnWrite();
      instance.clearExpiresAt();
      return this;
    }

    /**
     * <code>string domain = 4;</code>
     * @return The domain.
     */
    @java.lang.Override
    public java.lang.String getDomain() {
      return instance.getDomain();
    }
    /**
     * <code>string domain = 4;</code>
     * @return The bytes for domain.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDomainBytes() {
      return instance.getDomainBytes();
    }
    /**
     * <code>string domain = 4;</code>
     * @param value The domain to set.
     * @return This builder for chaining.
     */
    public Builder setDomain(
        java.lang.String value) {
      copyOnWrite();
      instance.setDomain(value);
      return this;
    }
    /**
     * <code>string domain = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDomain() {
      copyOnWrite();
      instance.clearDomain();
      return this;
    }
    /**
     * <code>string domain = 4;</code>
     * @param value The bytes for domain to set.
     * @return This builder for chaining.
     */
    public Builder setDomainBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDomainBytes(value);
      return this;
    }

    /**
     * <code>string path = 5;</code>
     * @return The path.
     */
    @java.lang.Override
    public java.lang.String getPath() {
      return instance.getPath();
    }
    /**
     * <code>string path = 5;</code>
     * @return The bytes for path.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPathBytes() {
      return instance.getPathBytes();
    }
    /**
     * <code>string path = 5;</code>
     * @param value The path to set.
     * @return This builder for chaining.
     */
    public Builder setPath(
        java.lang.String value) {
      copyOnWrite();
      instance.setPath(value);
      return this;
    }
    /**
     * <code>string path = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPath() {
      copyOnWrite();
      instance.clearPath();
      return this;
    }
    /**
     * <code>string path = 5;</code>
     * @param value The bytes for path to set.
     * @return This builder for chaining.
     */
    public Builder setPathBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPathBytes(value);
      return this;
    }

    /**
     * <code>bool secure = 6;</code>
     * @return The secure.
     */
    @java.lang.Override
    public boolean getSecure() {
      return instance.getSecure();
    }
    /**
     * <code>bool secure = 6;</code>
     * @param value The secure to set.
     * @return This builder for chaining.
     */
    public Builder setSecure(boolean value) {
      copyOnWrite();
      instance.setSecure(value);
      return this;
    }
    /**
     * <code>bool secure = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSecure() {
      copyOnWrite();
      instance.clearSecure();
      return this;
    }

    /**
     * <code>bool httpOnly = 7;</code>
     * @return The httpOnly.
     */
    @java.lang.Override
    public boolean getHttpOnly() {
      return instance.getHttpOnly();
    }
    /**
     * <code>bool httpOnly = 7;</code>
     * @param value The httpOnly to set.
     * @return This builder for chaining.
     */
    public Builder setHttpOnly(boolean value) {
      copyOnWrite();
      instance.setHttpOnly(value);
      return this;
    }
    /**
     * <code>bool httpOnly = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearHttpOnly() {
      copyOnWrite();
      instance.clearHttpOnly();
      return this;
    }

    /**
     * <code>bool hostOnly = 8;</code>
     * @return The hostOnly.
     */
    @java.lang.Override
    public boolean getHostOnly() {
      return instance.getHostOnly();
    }
    /**
     * <code>bool hostOnly = 8;</code>
     * @param value The hostOnly to set.
     * @return This builder for chaining.
     */
    public Builder setHostOnly(boolean value) {
      copyOnWrite();
      instance.setHostOnly(value);
      return this;
    }
    /**
     * <code>bool hostOnly = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearHostOnly() {
      copyOnWrite();
      instance.clearHostOnly();
      return this;
    }

    /**
     * <code>bool persistent = 9;</code>
     * @return The persistent.
     */
    @java.lang.Override
    public boolean getPersistent() {
      return instance.getPersistent();
    }
    /**
     * <code>bool persistent = 9;</code>
     * @param value The persistent to set.
     * @return This builder for chaining.
     */
    public Builder setPersistent(boolean value) {
      copyOnWrite();
      instance.setPersistent(value);
      return this;
    }
    /**
     * <code>bool persistent = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearPersistent() {
      copyOnWrite();
      instance.clearPersistent();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:CookieInfo)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.composepractice.CookieInfo();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "name_",
            "value_",
            "expiresAt_",
            "domain_",
            "path_",
            "secure_",
            "httpOnly_",
            "hostOnly_",
            "persistent_",
          };
          java.lang.String info =
              "\u0000\t\u0000\u0000\u0001\t\t\u0000\u0000\u0000\u0001\u0208\u0002\u0208\u0003\u0002" +
              "\u0004\u0208\u0005\u0208\u0006\u0007\u0007\u0007\b\u0007\t\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.composepractice.CookieInfo> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.composepractice.CookieInfo.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.composepractice.CookieInfo>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:CookieInfo)
  private static final com.example.composepractice.CookieInfo DEFAULT_INSTANCE;
  static {
    CookieInfo defaultInstance = new CookieInfo();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CookieInfo.class, defaultInstance);
  }

  public static com.example.composepractice.CookieInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CookieInfo> PARSER;

  public static com.google.protobuf.Parser<CookieInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

