// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cookie_store.proto

package com.example.composepractice;

public final class CookieStoreOuterClass {
  private CookieStoreOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
