// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: music_settings.proto

package com.example.composepractice;

public final class MusicSettingsOuterClass {
  private MusicSettingsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
