// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: music_settings.proto

package com.example.composepractice;

public interface MusicSettingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MusicSettings)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 user_account_id = 1;</code>
   * @return The userAccountId.
   */
  long getUserAccountId();
}
