// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: music_settings.proto

package com.example.composepractice;

/**
 * Protobuf type {@code MusicSettings}
 */
public  final class MusicSettings extends
    com.google.protobuf.GeneratedMessageLite<
        MusicSettings, MusicSettings.Builder> implements
    // @@protoc_insertion_point(message_implements:MusicSettings)
    MusicSettingsOrBuilder {
  private MusicSettings() {
  }
  public static final int USER_ACCOUNT_ID_FIELD_NUMBER = 1;
  private long userAccountId_;
  /**
   * <code>int64 user_account_id = 1;</code>
   * @return The userAccountId.
   */
  @java.lang.Override
  public long getUserAccountId() {
    return userAccountId_;
  }
  /**
   * <code>int64 user_account_id = 1;</code>
   * @param value The userAccountId to set.
   */
  private void setUserAccountId(long value) {
    
    userAccountId_ = value;
  }
  /**
   * <code>int64 user_account_id = 1;</code>
   */
  private void clearUserAccountId() {
    
    userAccountId_ = 0L;
  }

  public static com.example.composepractice.MusicSettings parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.composepractice.MusicSettings parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.composepractice.MusicSettings parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.composepractice.MusicSettings parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.composepractice.MusicSettings parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.composepractice.MusicSettings parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.composepractice.MusicSettings parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.composepractice.MusicSettings parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.composepractice.MusicSettings parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.composepractice.MusicSettings parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.composepractice.MusicSettings parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.composepractice.MusicSettings parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.composepractice.MusicSettings prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code MusicSettings}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.composepractice.MusicSettings, Builder> implements
      // @@protoc_insertion_point(builder_implements:MusicSettings)
      com.example.composepractice.MusicSettingsOrBuilder {
    // Construct using com.example.composepractice.MusicSettings.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int64 user_account_id = 1;</code>
     * @return The userAccountId.
     */
    @java.lang.Override
    public long getUserAccountId() {
      return instance.getUserAccountId();
    }
    /**
     * <code>int64 user_account_id = 1;</code>
     * @param value The userAccountId to set.
     * @return This builder for chaining.
     */
    public Builder setUserAccountId(long value) {
      copyOnWrite();
      instance.setUserAccountId(value);
      return this;
    }
    /**
     * <code>int64 user_account_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserAccountId() {
      copyOnWrite();
      instance.clearUserAccountId();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:MusicSettings)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.composepractice.MusicSettings();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "userAccountId_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0002";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.composepractice.MusicSettings> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.composepractice.MusicSettings.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.composepractice.MusicSettings>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:MusicSettings)
  private static final com.example.composepractice.MusicSettings DEFAULT_INSTANCE;
  static {
    MusicSettings defaultInstance = new MusicSettings();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      MusicSettings.class, defaultInstance);
  }

  public static com.example.composepractice.MusicSettings getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<MusicSettings> PARSER;

  public static com.google.protobuf.Parser<MusicSettings> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

