package com.example.composewidget.navigation

object Screen {
    const val main = "main"
    const val animation = "animation"
    const val canvas = "canvas"
    const val canvas2 = "canvas2"
    const val custom_layout = "custom_layout"
    const val gesture = "gesture"
    const val image = "image"
    const val layout = "layout"
    const val remember = "remember"
    object CanvasList{
        const val main = "canvas/main"
        const val drawLine = "canvas/drawLine"
        const val drawRect = "canvas/drawRect"
        const val drawImage  = "canvas/drawImage"
        const val drawCircle = "canvas/drawCircle"
        const val drawOval = "canvas/drawOval"
        const val drawArc = "canvas/drawArc"
        const val drawPath = "canvas/drawPath"
        const val drawPoints = "canvas/drawPoints"
        const val inset = "canvas/inset"
        const val translate = "canvas/translate"
        const val rotate = "canvas/rotate"
        const val rotateRad = "canvas/rotateRad"
        const val scale = "canvas/scale"
        const val clipRect = "canvas/clipRect"
        const val clipPath = "canvas/clipPath"
        const val drawIntoCanvas = "canvas/drawIntoCanvas"
        const val withTransform = "canvas/withTransform"
        const val drawWithContent = "canvas/drawWithContent"
        const val BlendMode = "canvas/BlendMode"

    }
    object List {
        const val main = "list/main"
        const val scrollable_row = "list/scrollable_row"
        const val scrollable_column = "list/scrollable_column"
        const val lazy_row = "list/lazy_row"
        const val lazy_column = "list/lazy_column"
        const val sticky_header = "list/sticky_header"
        const val lazy_vertical_grid = "list/lazy_vertical_grid"
    }

    const val text = "text"
    const val theme = "theme"
    const val editText = "editText"
    const val animation_other = "animation_other"
    const val dialog = "dialog"
    const val AlertDialog = "AlertDialog"
    const val DropdownMenu = "DropdownMenu"
    const val Popup = "Popup"
    const val BottomSheetScaffold = "BottomSheetScaffold"
    const val ModalBottomSheet = "ModalBottomSheet"
    const val BackdropScaffold = "BackdropScaffold"
    const val TopAppBar ="TopAppBar"
    const val BottomAppBar = "BottomAppBar"
    const val SnackBar = "SnackBar"
    const val ModalDrawer = "ModalDrawer"
    const val BottomDrawer = "BottomDrawer"
    const val BottomNavigation = "BottomNavigation"
    const val ListItem = "ListItem"
}